version: '3.8'

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: tinder_gamer_proxy
    # Expõe a porta 80 para o mundo e a mapeia para a porta 80 do container
    ports:
      - "80:80"
    volumes:
      # Mapeia seu arquivo de configuração para dentro do container
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api # O Nginx só inicia depois que a API estiver pronta

  api:
    container_name: tinder_gamer_api_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    # NÃO precisa mais expor a porta (8001).
    # Apenas o Nginx falará com ela.
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      ALGORITHM: ${ALGORITHM:-HS256}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      ENVIRONMENT: production
      DEBUG: "false"
    restart: unless-stopped
