"""Add is_active and games fields to users table

Revision ID: d7c04876bcc6
Revises: 6c06e844996d
Create Date: 2025-09-26 04:42:02.946182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7c04876bcc6'
down_revision: Union[str, Sequence[str], None] = '6c06e844996d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Adicionar coluna is_active com valor padrão True
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))
    # Adicionar coluna games com valor padrão array vazio
    op.add_column('users', sa.Column('games', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'games')
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
