"""Change games array to game string and clean data

Revision ID: e42b2a0edd12
Revises: d7c04876bcc6
Create Date: 2025-09-26 05:04:27.521961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e42b2a0edd12'
down_revision: Union[str, Sequence[str], None] = 'd7c04876bcc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('game', sa.String(), nullable=True))
    op.drop_column('users', 'games')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('games', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False))
    op.drop_column('users', 'game')
    # ### end Alembic commands ###
